use crate::paths;
use anyhow::Result;
use std::fs;
use std::path::Path;

pub fn are_steamui_chunks_patched() -> bool {
    let steamui_dir = paths::steam_data_dir().join("Steam.AppBundle/Steam/Contents/MacOS/steamui");
    if !steamui_dir.is_dir() {
        return true;
    }

    if let Ok(entries) = fs::read_dir(&steamui_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
            if !name.starts_with("chunk~") || !name.ends_with(".js") || name.ends_with(".bak") {
                continue;
            }

            if let Ok(content) = fs::read_to_string(&path) {
                let is_candidate = content.contains("case u.Ul.jw:return s.UM;")
                    || content.contains("case D.Ul.pd:case D.Ul.K5:case D.Ul.KR:case D.Ul.Mu:return!0")
                    || content.contains("(!o||\"darwin\"!=o)&&(!l||\"darwin\"!=l)")
                    || content.contains("r.k_EClientUINotification_FamilySharingDeviceAvailable,v=r.k_EClientUINotification_SteamPlay")
                    || content.contains("\"Playable on this computer via Steam Play\"");

                if is_candidate {
                    let has_patches = content.contains("\"Playable via Steam Play (Nucleon)\"")
                        || content.contains("get is_invalid_os_type(){return false}");
                    if !has_patches {
                        return false;
                    }
                }
            }
        }
    }
    true
}

/// Deletes Steam CEF script and shader caches so modified WebUI scripts load immediately,
/// while safely preserving Chromium profile databases (Web Data, Cookies, Preferences, Login Data).
pub fn clear_cef_cache() -> Result<()> {
    let htmlcache = paths::home_dir().join("Library/Application Support/Steam/config/htmlcache");
    if !htmlcache.is_dir() {
        return Ok(());
    }

    let cache_targets = [
        htmlcache.join("Default/Cache"),
        htmlcache.join("Default/Code Cache"),
        htmlcache.join("Default/GPUCache"),
        htmlcache.join("Default/DawnGraphiteCache"),
        htmlcache.join("Default/DawnWebGPUCache"),
        htmlcache.join("GrShaderCache"),
        htmlcache.join("ShaderCache"),
        htmlcache.join("GraphiteDawnCache"),
    ];

    for target in &cache_targets {
        if target.exists() {
            let _ = fs::remove_dir_all(target);
        }
    }

    // Clean up any old_* directories generated by Chromium
    if let Ok(entries) = fs::read_dir(&htmlcache) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.starts_with("old_") {
                let _ = fs::remove_dir_all(entry.path());
            }
        }
    }
    if let Ok(entries) = fs::read_dir(htmlcache.join("Default")) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.starts_with("old_") {
                let _ = fs::remove_dir_all(entry.path());
            }
        }
    }

    log::info!(
        "Safely cleared Steam CEF script/shader caches without disturbing user profile data"
    );
    Ok(())
}

/// Patches Steam CEF WebUI chunks on disk with exact size-preserving padding
/// so that Steam's bootstrapper passes file verification without downloading updates,
/// while the WebUI gets full Steam Play / compatibility functionality (Play/Install enabled,
/// no crossed-out prohibition icons, Compatibility tab unlocked).
pub fn patch_steamui_chunks() -> Result<usize> {
    let steamui_dir = paths::steam_data_dir().join("Steam.AppBundle/Steam/Contents/MacOS/steamui");
    if !steamui_dir.is_dir() {
        return Ok(0);
    }

    // Try reading expected file sizes from package manifest if available
    let package_manifest = paths::steam_data_dir()
        .join("Steam.AppBundle/Steam/Contents/MacOS/package/steam_client_osx.installed");
    let mut expected_sizes: std::collections::HashMap<String, usize> =
        std::collections::HashMap::new();
    if let Ok(manifest_content) = fs::read_to_string(&package_manifest) {
        for line in manifest_content.lines() {
            let parts: Vec<&str> = line.split(',').collect();
            if parts.len() >= 2 {
                let filename = parts[0].trim().trim_start_matches("steamui/");
                if let Some(size_part) = parts[1].split(';').next() {
                    if let Ok(sz) = size_part.trim().parse::<usize>() {
                        expected_sizes.insert(filename.to_string(), sz);
                    }
                }
            }
        }
    }

    let mut patched_count = 0;

    if let Ok(entries) = fs::read_dir(&steamui_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
            if !name.starts_with("chunk~") || !name.ends_with(".js") || name.ends_with(".bak") {
                continue;
            }

            let raw_bytes = match fs::read(&path) {
                Ok(b) => b,
                Err(_) => continue,
            };

            let expected_size = expected_sizes.get(name).copied().unwrap_or(raw_bytes.len());

            let content = match String::from_utf8(raw_bytes) {
                Ok(c) => c,
                Err(_) => continue,
            };

            // Check if already patched and matching expected size
            if content.contains("\"Playable via Steam Play (Nucleon)\"")
                && content.contains("get is_invalid_os_type(){return false}")
                && !content.contains("(0,h.we)\"Enable Nucleon")
                && content.len() == expected_size
            {
                continue;
            }

            let mut modified = content;
            let mut changed = false;

            // 1. Enable Install button in PlayBar (_e returns s.UM "Install" for u.Ul.KR)
            let target_install_btn = "case u.Ul.jw:return s.UM;";
            let repl_install_btn = "case u.Ul.jw:case u.Ul.KR:return s.UM;";
            if modified.contains(target_install_btn) {
                modified = modified.replace(target_install_btn, repl_install_btn);
                changed = true;
            }

            // 2. Do not treat InvalidPlatform as permanently unavailable
            let target_perm_unavail =
                "case D.Ul.pd:case D.Ul.K5:case D.Ul.KR:case D.Ul.Mu:return!0";
            let repl_perm_unavail = "case D.Ul.pd:case D.Ul.K5:case D.Ul.Mu:return!0";
            if modified.contains(target_perm_unavail) {
                modified = modified.replace(target_perm_unavail, repl_perm_unavail);
                changed = true;
            }

            // 3. Make is_available_on_current_platform return true
            let target_avail_platform = "get is_available_on_current_platform(){return this.local_per_client_data&&this.local_per_client_data.is_available_on_current_platform}";
            let repl_avail_platform = "get is_available_on_current_platform(){return true}";
            if modified.contains(target_avail_platform) {
                modified = modified.replace(target_avail_platform, repl_avail_platform);
                changed = true;
            }

            // 4. Force is_invalid_os_type to false -> Removes crossed prohibition icon & enables Install/Play in Steam UI
            let target_invalid_os = "get is_invalid_os_type(){return this.most_available_per_client_data.is_invalid_os_type}";
            let repl_invalid_os = "get is_invalid_os_type(){return false}";
            if modified.contains(target_invalid_os) {
                modified = modified.replace(target_invalid_os, repl_invalid_os);
                changed = true;
            }

            // 5. Replace InvalidPlatform status text with "Playable via Steam Play (Nucleon)"
            let target_status_text = r##"(0,W.we)("#DisplayStatus_InvalidPlatform")"##;
            let repl_status_text = r##""Playable via Steam Play (Nucleon)""##;
            if modified.contains(target_status_text) {
                modified = modified.replace(target_status_text, repl_status_text);
                changed = true;
            }

            // 6. Do not exclude InvalidPlatform games from collection platform filter
            let target_filter = "r&&e.BIsPerClientDataLocal(r)&&r.display_status==ze.Ul.KR&&(t=!1)";
            let repl_filter = "false&&(t=!1)";
            if modified.contains(target_filter) {
                modified = modified.replace(target_filter, repl_filter);
                changed = true;
            }

            // 7. Enable Compatibility tab in Game Properties
            let target_compat =
                r##"(0,f.CI)()&&o.push({title:(0,A.we)("#AppProperties_CompatibilityPage")"##;
            let repl_compat =
                r##"true&&o.push({title:(0,A.we)("#AppProperties_CompatibilityPage")"##;
            if modified.contains(target_compat) {
                modified = modified.replace(target_compat, repl_compat);
                changed = true;
            }

            // 8. Always enable Compatibility tool force checkbox in Game Properties
            let target_compat_enabled = "()=>u.rV.settings.bCompatEnabled";
            let repl_compat_enabled = "()=>true";
            if modified.contains(target_compat_enabled) {
                modified = modified.replace(target_compat_enabled, repl_compat_enabled);
                changed = true;
            }

            // 9. Compatibility tab in Steam Settings
            let target_settings = "Compatibility:{visible:t&&(0,f.CI)()&&!(0,f.rf)()";
            let repl_settings = "Compatibility:{visible:t&&true&&!(0,f.rf)()";
            if modified.contains(target_settings) {
                modified = modified.replace(target_settings, repl_settings);
                changed = true;
            }

            // 10. Fallback global compat tool in Steam Settings dropdown
            let target_tool_default = "const t=(0,c.t0)().strCompatTool,";
            let repl_tool_default =
                r#"const t=(0,c.t0)().strCompatTool||(A.length?A[0].data:"nucleon"),"#;
            if modified.contains(target_tool_default) {
                modified = modified.replace(target_tool_default, repl_tool_default);
                changed = true;
            }

            // 11. SteamPlay section in Steam Settings
            if modified.contains("function ue(e){return(0,T.CI)()?") {
                modified = modified.replace(
                    "function ue(e){return(0,T.CI)()?",
                    "function ue(e){return true?",
                );
                changed = true;
            }

            // 12. Add Non-Steam EXE filter
            let target_exe = r##"("#AddNonSteam_Filter_Exe_MacOS"),rFilePatterns:["*.app"]"##;
            let repl_exe = r##"("#AddNonSteam_Filter_Exe_MacOS"),rFilePatterns:["*.app","*.exe"]"##;
            if modified.contains(target_exe) {
                modified = modified.replace(target_exe, repl_exe);
                changed = true;
            }

            // 13. Allow .exe in image / executable filters
            let target_img = r##"{strFileTypeName:"Image Files (*.tga,*.png)",rFilePatterns:["*.tga","*.png"]}"##;
            let repl_img = r##"{strFileTypeName:"Image Files (*.tga,*.png,*.exe)",rFilePatterns:["*.tga","*.png","*.exe"]}"##;
            if modified.contains(target_img) {
                modified = modified.replace(target_img, repl_img);
                changed = true;
            }

            // 14. Game list entry notice for Windows apps
            let target_entry = r##"(0,h.we)("#GameList_Entry_Invalid_OSType2")"##;
            let repl_entry = r##""Enable Nucleon under Properties > Compatibility to install and run the Windows version.""##;
            if modified.contains(target_entry) {
                modified = modified.replace(target_entry, repl_entry);
                changed = true;
            }
            if modified.contains("(0,h.we)\"Enable Nucleon") {
                modified = modified.replace("(0,h.we)\"Enable Nucleon", "\"Enable Nucleon");
                changed = true;
            }

            if changed {
                // Strip any existing padding comment before recalculating
                if let Some(pos) = modified.rfind("/*") {
                    if modified[pos..].ends_with("*/") && modified[pos..].contains('*') {
                        modified.truncate(pos);
                    }
                }

                // Exact-size padding: ensure modified.len() == expected_size
                let new_len = modified.len();
                if new_len < expected_size {
                    let diff = expected_size - new_len;
                    if diff >= 4 {
                        let pad = format!("/*{}*/", "*".repeat(diff - 4));
                        modified.push_str(&pad);
                    } else {
                        modified.push_str(&" ".repeat(diff));
                    }
                }

                #[cfg(unix)]
                {
                    use std::os::unix::fs::PermissionsExt;
                    if let Ok(meta) = fs::metadata(&path) {
                        let mut perms = meta.permissions();
                        perms.set_mode(0o755);
                        let _ = fs::set_permissions(&path, perms);
                    }
                }

                let _ = fs::write(&path, modified);

                #[cfg(unix)]
                {
                    use std::os::unix::fs::PermissionsExt;
                    if let Ok(meta) = fs::metadata(&path) {
                        let mut perms = meta.permissions();
                        perms.set_mode(0o755);
                        let _ = fs::set_permissions(&path, perms);
                    }
                }

                log::info!(
                    "Patched SteamUI chunk {} (size preserved: {} bytes)",
                    name,
                    expected_size
                );
                patched_count += 1;
            }
        }
    }

    if patched_count > 0 {
        let _ = clear_cef_cache();
    }

    Ok(patched_count)
}

/// Reverts modified Steam WebUI chunks in the specified steamui directory and flushes CEF cache.
pub fn restore_steamui_chunks_in(steamui_dir: &Path) -> Result<usize> {
    if !steamui_dir.is_dir() {
        return Ok(0);
    }

    let package_manifest = paths::steam_data_dir()
        .join("Steam.AppBundle/Steam/Contents/MacOS/package/steam_client_osx.installed");
    let mut expected_sizes: std::collections::HashMap<String, usize> =
        std::collections::HashMap::new();
    if let Ok(manifest_content) = fs::read_to_string(&package_manifest) {
        for line in manifest_content.lines() {
            let parts: Vec<&str> = line.split(',').collect();
            if parts.len() >= 2 {
                let filename = parts[0].trim().trim_start_matches("steamui/");
                if let Some(size_part) = parts[1].split(';').next() {
                    if let Ok(sz) = size_part.trim().parse::<usize>() {
                        expected_sizes.insert(filename.to_string(), sz);
                    }
                }
            }
        }
    }

    let mut restored_count = 0;

    if let Ok(entries) = fs::read_dir(steamui_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
            if !name.starts_with("chunk~") || !name.ends_with(".js") || name.ends_with(".bak") {
                continue;
            }

            let raw_bytes = match fs::read(&path) {
                Ok(b) => b,
                Err(_) => continue,
            };

            let expected_size = expected_sizes.get(name).copied().unwrap_or(raw_bytes.len());

            let content = match String::from_utf8(raw_bytes) {
                Ok(c) => c,
                Err(_) => continue,
            };

            let is_patched = content.contains("\"Playable via Steam Play (Nucleon)\"")
                || content.contains("get is_invalid_os_type(){return false}")
                || content.contains("Enable Nucleon under Properties")
                || content.contains("case u.Ul.jw:case u.Ul.KR:return s.UM;");

            if !is_patched {
                continue;
            }

            let mut modified = content;
            let mut changed = false;

            // 1. Revert Install button
            let repl_install_btn = "case u.Ul.jw:case u.Ul.KR:return s.UM;";
            let target_install_btn = "case u.Ul.jw:return s.UM;";
            if modified.contains(repl_install_btn) {
                modified = modified.replace(repl_install_btn, target_install_btn);
                changed = true;
            }

            // 2. Revert InvalidPlatform permanence
            let repl_perm_unavail = "case D.Ul.pd:case D.Ul.K5:case D.Ul.Mu:return!0";
            let target_perm_unavail =
                "case D.Ul.pd:case D.Ul.K5:case D.Ul.KR:case D.Ul.Mu:return!0";
            if modified.contains(repl_perm_unavail) {
                modified = modified.replace(repl_perm_unavail, target_perm_unavail);
                changed = true;
            }

            // 3. Revert is_available_on_current_platform
            let repl_avail_platform = "get is_available_on_current_platform(){return true}";
            let target_avail_platform = "get is_available_on_current_platform(){return this.local_per_client_data&&this.local_per_client_data.is_available_on_current_platform}";
            if modified.contains(repl_avail_platform) {
                modified = modified.replace(repl_avail_platform, target_avail_platform);
                changed = true;
            }

            // 4. Revert is_invalid_os_type
            let repl_invalid_os = "get is_invalid_os_type(){return false}";
            let target_invalid_os =
                "get is_invalid_os_type(){return this.most_available_per_client_data.is_invalid_os_type}";
            if modified.contains(repl_invalid_os) {
                modified = modified.replace(repl_invalid_os, target_invalid_os);
                changed = true;
            }

            // 5. Revert status text
            let repl_status_text = r##""Playable via Steam Play (Nucleon)""##;
            let target_status_text = r##"(0,W.we)("#DisplayStatus_InvalidPlatform")"##;
            if modified.contains(repl_status_text) {
                modified = modified.replace(repl_status_text, target_status_text);
                changed = true;
            }

            // 6. Revert collection filter
            let repl_filter = "false&&(t=!1)";
            let target_filter = "r&&e.BIsPerClientDataLocal(r)&&r.display_status==ze.Ul.KR&&(t=!1)";
            if modified.contains(repl_filter) {
                modified = modified.replace(repl_filter, target_filter);
                changed = true;
            }

            // 7. Revert Compatibility tab in Game Properties
            let repl_compat =
                r##"true&&o.push({title:(0,A.we)("#AppProperties_CompatibilityPage")"##;
            let target_compat =
                r##"(0,f.CI)()&&o.push({title:(0,A.we)("#AppProperties_CompatibilityPage")"##;
            if modified.contains(repl_compat) {
                modified = modified.replace(repl_compat, target_compat);
                changed = true;
            }

            // 8. Revert settings compatibility
            let repl_settings = "Compatibility:{visible:t&&true&&!(0,f.rf)()";
            let target_settings = "Compatibility:{visible:t&&(0,f.CI)()&&!(0,f.rf)()";
            if modified.contains(repl_settings) {
                modified = modified.replace(repl_settings, target_settings);
                changed = true;
            }

            // 9. Revert global compat tool default
            let repl_tool_default =
                r#"const t=(0,c.t0)().strCompatTool||(A.length?A[0].data:"nucleon"),"#;
            let target_tool_default = "const t=(0,c.t0)().strCompatTool,";
            if modified.contains(repl_tool_default) {
                modified = modified.replace(repl_tool_default, target_tool_default);
                changed = true;
            }

            // 10. Revert SteamPlay section
            if modified.contains("function ue(e){return true?") {
                modified = modified.replace(
                    "function ue(e){return true?",
                    "function ue(e){return(0,T.CI)()?",
                );
                changed = true;
            }

            // 11. Revert Non-Steam EXE filter
            let repl_exe = r##"("#AddNonSteam_Filter_Exe_MacOS"),rFilePatterns:["*.app","*.exe"]"##;
            let target_exe = r##"("#AddNonSteam_Filter_Exe_MacOS"),rFilePatterns:["*.app"]"##;
            if modified.contains(repl_exe) {
                modified = modified.replace(repl_exe, target_exe);
                changed = true;
            }

            // 12. Revert image / executable filters
            let repl_img = r##"{strFileTypeName:"Image Files (*.tga,*.png,*.exe)",rFilePatterns:["*.tga","*.png","*.exe"]}"##;
            let target_img = r##"{strFileTypeName:"Image Files (*.tga,*.png)",rFilePatterns:["*.tga","*.png"]}"##;
            if modified.contains(repl_img) {
                modified = modified.replace(repl_img, target_img);
                changed = true;
            }

            // 13. Revert game list entry notice
            let repl_entry1 = "\"Enable Nucleon under Properties > Compatibility to install and run the Windows version.\"";
            let repl_entry2 = "(0,h.we)\"Enable Nucleon under Properties > Compatibility to install and run the Windows version.\"";
            let target_entry = r##"(0,h.we)("#GameList_Entry_Invalid_OSType2")"##;
            if modified.contains(repl_entry2) {
                modified = modified.replace(repl_entry2, target_entry);
                changed = true;
            } else if modified.contains(repl_entry1) {
                modified = modified.replace(repl_entry1, target_entry);
                changed = true;
            }

            if changed {
                // Strip padding comment before recalculating
                if let Some(pos) = modified.rfind("/*") {
                    if modified[pos..].ends_with("*/") && modified[pos..].contains('*') {
                        modified.truncate(pos);
                    }
                }

                // Exact-size padding: ensure modified.len() == expected_size
                let new_len = modified.len();
                if new_len < expected_size {
                    let diff = expected_size - new_len;
                    if diff >= 4 {
                        let pad = format!("/*{}*/", "*".repeat(diff - 4));
                        modified.push_str(&pad);
                    } else {
                        modified.push_str(&" ".repeat(diff));
                    }
                }

                #[cfg(unix)]
                {
                    use std::os::unix::fs::PermissionsExt;
                    if let Ok(meta) = fs::metadata(&path) {
                        let mut perms = meta.permissions();
                        perms.set_mode(0o755);
                        let _ = fs::set_permissions(&path, perms);
                    }
                }

                let _ = fs::write(&path, modified);
                restored_count += 1;
            }
        }
    }

    let _ = clear_cef_cache();
    Ok(restored_count)
}

/// Reverts all Steam WebUI chunk modifications on disk and clears CEF cache.
pub fn restore_steamui_chunks() -> Result<usize> {
    let steamui_dir = paths::steam_data_dir().join("Steam.AppBundle/Steam/Contents/MacOS/steamui");
    restore_steamui_chunks_in(&steamui_dir)
}
