[package]
name = "nucleon-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
tempfile = { workspace = true }
object = { workspace = true }
memchr = { workspace = true }
overlay-shim = { path = "../overlay-shim" }
plist = { workspace = true }
keyvalues-parser = { workspace = true }
nix = { version = "0.31", default-features = false, features = ["user"] }
ureq = { workspace = true }
zip = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }
zstd = { workspace = true }
memmap2 = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = { workspace = true }
core-foundation = { workspace = true }

[lints]
workspace = true
