[package]
name = "nucleon-hook"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]
name = "nucleon"

[dependencies]
frida-gum = { workspace = true }
frida-gum-sys = { workspace = true }

nucleon-core = { path = "../nucleon-core" }
anyhow = { workspace = true }
tempfile = { workspace = true }
env_logger = { workspace = true }
ctor = { workspace = true }
libc = { workspace = true }
object = { workspace = true }
memchr = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }

[lints]
workspace = true
